server:
  port: 8089
spring:
  application:
    name: studnetsocket

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry-vue?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8&useUnicode=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.mpq.mydesign : debug

#mybatis-plus:
#  type-aliases-package: com.hzzy.mpq.studnetsocket.mapper
#  mapper-locations: classpath*:mapper/*.xml

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hzzy.mpq.studnetsocket.mapper
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*.xml